Ronans-iMac-2017:CivilianPopulation rleroy$ mono ../../bin/netkan.exe --verbose CivilianPopulation.netkan 
89 [1] INFO CKAN.NetKAN.Program (null) - Transforming CivilianPopulation.netkan
124 [1] INFO CKAN.NetKAN.Program (null) - Using CKAN cache at /Users/rleroy/Games/KSP/1.3/KSP-with-addons/CKAN/downloads
168 [1] INFO CKAN.NetKAN.Program (null) - Finished reading input
169 [1] INFO CKAN.NetKAN.Validators.HasIdentifierValidator (null) - Validating that metadata contains an identifier
169 [1] INFO CKAN.NetKAN.Program (null) - Input successfully passed pre-validation
198 [1] INFO CKAN.NetKAN.Transformers.DownloadAttributeTransformer (null) - Executing Download Attribute transformation with 
542 [1] INFO CKAN.NetKAN.Transformers.GeneratedByTransformer (null) - Executing Generated By transformation with 
542 [1] INFO CKAN.NetKAN.Transformers.StripNetkanMetadataTransformer (null) - Executing Strip Netkan Metadata transformation with 
543 [1] INFO CKAN.NetKAN.Transformers.PropertySortTransformer (null) - Executing property sort transformation
547 [1] INFO CKAN.NetKAN.Program (null) - Finished transformation
682 [1] INFO CKAN.NetKAN.Program (null) - Output successfully passed post-validation
684 [1] INFO CKAN.NetKAN.Program (null) - Transformation written to ./CivilianPopulation-2.0.4.ckan
Ronans-iMac-2017:CivilianPopulation rleroy$ mono ../../bin/ckan.exe install -c CivilianPopulation-2.0.4.ckan
About to install...

 * Civilian Population 2.0.4

Continue? [Y/n] Y

Downloading "http://nexus.amis.tv/repository/maven-releases/tv/amis/pamynx/ksp-civilian-population-mod/2.0.4/ksp-civilian-population-mod-2.0.4.zip"
0 kbps - downloading - 0 MB left - 100%           
Installing mod "CivilianPopulation 2.0.4"
Unhandled Exception:
CKAN.FileNotFoundKraken: Trying to install CivilianPopulation 2.0.4, but it's not downloaded or download is corrupted
  at CKAN.ModuleInstaller.Install (CKAN.CkanModule module, System.String filename) [0x00073] in <9899496520cf4295b5007987e777576e>:0 
  at CKAN.ModuleInstaller.InstallList (System.Collections.Generic.ICollection`1[T] modules, CKAN.RelationshipResolverOptions options, CKAN.IDownloader downloader) [0x00183] in <9899496520cf4295b5007987e777576e>:0 
  at CKAN.ModuleInstaller.InstallList (System.Collections.Generic.List`1[T] modules, CKAN.RelationshipResolverOptions options, CKAN.IDownloader downloader) [0x00028] in <9899496520cf4295b5007987e777576e>:0 
  at CKAN.CmdLine.Install.RunCommand (CKAN.KSP ksp, System.Object raw_options) [0x00198] in <9899496520cf4295b5007987e777576e>:0 
  at CKAN.CmdLine.MainClass.RunAction (CKAN.CmdLine.Options cmdline, CKAN.CmdLine.CommonOptions options, System.String[] args, CKAN.IUser user, CKAN.KSPManager manager) [0x00305] in <9899496520cf4295b5007987e777576e>:0 
  at CKAN.CmdLine.MainClass.Main (System.String[] args) [0x00312] in <9899496520cf4295b5007987e777576e>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: CKAN.FileNotFoundKraken: Trying to install CivilianPopulation 2.0.4, but it's not downloaded or download is corrupted
  at CKAN.ModuleInstaller.Install (CKAN.CkanModule module, System.String filename) [0x00073] in <9899496520cf4295b5007987e777576e>:0 
  at CKAN.ModuleInstaller.InstallList (System.Collections.Generic.ICollection`1[T] modules, CKAN.RelationshipResolverOptions options, CKAN.IDownloader downloader) [0x00183] in <9899496520cf4295b5007987e777576e>:0 
  at CKAN.ModuleInstaller.InstallList (System.Collections.Generic.List`1[T] modules, CKAN.RelationshipResolverOptions options, CKAN.IDownloader downloader) [0x00028] in <9899496520cf4295b5007987e777576e>:0 
  at CKAN.CmdLine.Install.RunCommand (CKAN.KSP ksp, System.Object raw_options) [0x00198] in <9899496520cf4295b5007987e777576e>:0 
  at CKAN.CmdLine.MainClass.RunAction (CKAN.CmdLine.Options cmdline, CKAN.CmdLine.CommonOptions options, System.String[] args, CKAN.IUser user, CKAN.KSPManager manager) [0x00305] in <9899496520cf4295b5007987e777576e>:0 
  at CKAN.CmdLine.MainClass.Main (System.String[] args) [0x00312] in <9899496520cf4295b5007987e777576e>:0 
Ronans-iMac-2017:CivilianPopulation rleroy$ 
